// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.TestServerApi
{
	/// <summary>
	/// Request for FinishTest.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class FinishTestRequestDto : ServiceDto<FinishTestRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public FinishTestRequestDto()
		{
		}

		/// <summary>
		/// The response from the client request.
		/// </summary>
		public JObject Response { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(FinishTestRequestDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentObjects(Response, other.Response);
		}
	}
}
