// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.TestServerApi
{
	/// <summary>
	/// Response for FinishTest.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class FinishTestResponseDto : ServiceDto<FinishTestResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public FinishTestResponseDto()
		{
		}

		/// <summary>
		/// The test status.
		/// </summary>
		public TestStatus? Status { get; set; }

		/// <summary>
		/// The test message.
		/// </summary>
		public string Message { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(FinishTestResponseDto other)
		{
			return other != null &&
				Status == other.Status &&
				Message == other.Message;
		}
	}
}
