// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.TestServerApi
{
	/// <summary>
	/// Request for GetApiInfo.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetApiInfoRequestDto : ServiceDto<GetApiInfoRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetApiInfoRequestDto()
		{
		}

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetApiInfoRequestDto other)
		{
			return other != null;
		}
	}
}
