// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;

namespace Facility.TestServerApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public partial interface ITestServerApi
	{
		Task<ServiceResult<GetApiInfoResponseDto>> GetApiInfoAsync(GetApiInfoRequestDto request, CancellationToken cancellationToken);
	}
}
