// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Response for CreateWidget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class CreateWidgetResponseDto : ServiceDto<CreateWidgetResponseDto>
	{
		/// <summary>
		/// The created widget.
		/// </summary>
		public WidgetDto Widget { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(CreateWidgetResponseDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalent(Widget, other.Widget);
		}
	}
}
