// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

#pragma warning disable 612 // member is obsolete

namespace Facility.ExampleApi
{
	/// <summary>
	/// Request for EditWidget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class EditWidgetRequestDto : ServiceDto<EditWidgetRequestDto>
	{
		/// <summary>
		/// The widget ID.
		/// </summary>
		public string Id { get; set; }

		/// <summary>
		/// The operations.
		/// </summary>
		public List<JObject> Ops { get; set; }

		/// <summary>
		/// The new weight.
		/// </summary>
		[Obsolete]
		public double? Weight { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(EditWidgetRequestDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalent(Id, other.Id) &&
				ServiceDataUtility.AreEquivalent(Ops, other.Ops) &&
				ServiceDataUtility.AreEquivalent(Weight, other.Weight);
		}
	}
}
