// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Response for EditWidget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class EditWidgetResponseDto : ServiceDto<EditWidgetResponseDto>
	{
		/// <summary>
		/// The edited widget.
		/// </summary>
		public WidgetDto Widget { get; set; }

		/// <summary>
		/// The pending job.
		/// </summary>
		public WidgetJobDto Job { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(EditWidgetResponseDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentDtos(Widget, other.Widget) &&
				ServiceDataUtility.AreEquivalentDtos(Job, other.Job);
		}
	}
}
