// DO NOT EDIT: generated by fsdgencsharp
using Facility.Core;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Custom errors.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class ExampleApiErrors
	{
		/// <summary>
		/// The user is not an administrator.
		/// </summary>
		public const string NotAdmin = "NotAdmin";

		/// <summary>
		/// The user is not an administrator.
		/// </summary>
		public static ServiceErrorDto CreateNotAdmin(string message = null)
		{
			return new ServiceErrorDto(NotAdmin, message ?? "The user is not an administrator.");
		}
	}
}
