// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Response for GetPreference.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetPreferenceResponseDto : ServiceDto<GetPreferenceResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetPreferenceResponseDto()
		{
		}

		/// <summary>
		/// The preference value.
		/// </summary>
		public PreferenceDto Value { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetPreferenceResponseDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentDtos(Value, other.Value);
		}
	}
}
