// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Request for GetWidget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetWidgetRequestDto : ServiceDto<GetWidgetRequestDto>
	{
		/// <summary>
		/// The widget ID.
		/// </summary>
		public string Id { get; set; }

		public string IfNoneMatch { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetWidgetRequestDto other)
		{
			return other != null &&
				Id == other.Id &&
				IfNoneMatch == other.IfNoneMatch;
		}
	}
}
