// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Response for GetWidgetWeight.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetWidgetWeightResponseDto : ServiceDto<GetWidgetWeightResponseDto>
	{
		/// <summary>
		/// The widget weight.
		/// </summary>
		public double? Value { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetWidgetWeightResponseDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalent(Value, other.Value);
		}
	}
}
