// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// A preference.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class PreferenceDto : ServiceDto<PreferenceDto>
	{
		[JsonProperty("boolean")]
		public bool? IsBoolean { get; set; }

		public IReadOnlyList<bool> Booleans { get; set; }

		public double? Double { get; set; }

		public IReadOnlyList<double> Doubles { get; set; }

		public int? Integer { get; set; }

		public IReadOnlyList<int> Integers { get; set; }

		public string String { get; set; }

		public IReadOnlyList<string> Strings { get; set; }

		public byte[] Bytes { get; set; }

		public IReadOnlyList<byte[]> Byteses { get; set; }

		public WidgetField? WidgetField { get; set; }

		public IReadOnlyList<WidgetField> WidgetFields { get; set; }

		public WidgetDto Widget { get; set; }

		public IReadOnlyList<WidgetDto> Widgets { get; set; }

		public ServiceResult<WidgetDto> Result { get; set; }

		public IReadOnlyList<ServiceResult<WidgetDto>> Results { get; set; }

		public long? BigInteger { get; set; }

		public IReadOnlyList<long> BigIntegers { get; set; }

		public ServiceErrorDto Error { get; set; }

		public IReadOnlyList<ServiceErrorDto> Errors { get; set; }

		public JObject Object { get; set; }

		public IReadOnlyList<JObject> Objects { get; set; }

		public IReadOnlyDictionary<string, string> NamedStrings { get; set; }

		public IReadOnlyDictionary<string, WidgetDto> NamedWidgets { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(PreferenceDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalent(IsBoolean, other.IsBoolean) &&
				ServiceDataUtility.AreEquivalent(Booleans, other.Booleans) &&
				ServiceDataUtility.AreEquivalent(Double, other.Double) &&
				ServiceDataUtility.AreEquivalent(Doubles, other.Doubles) &&
				ServiceDataUtility.AreEquivalent(Integer, other.Integer) &&
				ServiceDataUtility.AreEquivalent(Integers, other.Integers) &&
				ServiceDataUtility.AreEquivalent(String, other.String) &&
				ServiceDataUtility.AreEquivalent(Strings, other.Strings) &&
				ServiceDataUtility.AreEquivalent(Bytes, other.Bytes) &&
				ServiceDataUtility.AreEquivalent(Byteses, other.Byteses) &&
				ServiceDataUtility.AreEquivalent(WidgetField, other.WidgetField) &&
				ServiceDataUtility.AreEquivalent(WidgetFields, other.WidgetFields) &&
				ServiceDataUtility.AreEquivalent(Widget, other.Widget) &&
				ServiceDataUtility.AreEquivalent(Widgets, other.Widgets) &&
				ServiceDataUtility.AreEquivalent(Result, other.Result) &&
				ServiceDataUtility.AreEquivalent(Results, other.Results) &&
				ServiceDataUtility.AreEquivalent(BigInteger, other.BigInteger) &&
				ServiceDataUtility.AreEquivalent(BigIntegers, other.BigIntegers) &&
				ServiceDataUtility.AreEquivalent(Error, other.Error) &&
				ServiceDataUtility.AreEquivalent(Errors, other.Errors) &&
				ServiceDataUtility.AreEquivalent(Object, other.Object) &&
				ServiceDataUtility.AreEquivalent(Objects, other.Objects) &&
				ServiceDataUtility.AreEquivalent(NamedStrings, other.NamedStrings) &&
				ServiceDataUtility.AreEquivalent(NamedWidgets, other.NamedWidgets);
		}
	}
}
