// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

#pragma warning disable 612 // member is obsolete

namespace Facility.ExampleApi
{
	/// <summary>
	/// A widget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class WidgetDto : ServiceDto<WidgetDto>
	{
		/// <summary>
		/// A unique identifier for the widget.
		/// </summary>
		public string Id { get; set; }

		/// <summary>
		/// The name of the widget.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The weight of the widget.
		/// </summary>
		[Obsolete]
		public double? Weight { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(WidgetDto other)
		{
			return other != null &&
				Id == other.Id &&
				Name == other.Name &&
				Weight == other.Weight;
		}
	}
}
