// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using System.Net;

namespace Facility.ExampleApi.Http
{
	/// <summary>
	/// Custom errors.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class HttpExampleApiErrors
	{
		/// <summary>
		/// Gets the HTTP status code that corresponds to the specified error code.
		/// </summary>
		public static HttpStatusCode? TryGetHttpStatusCode(string errorCode)
		{
			int statusCode;
			return s_errorToStatus.TryGetValue(errorCode, out statusCode) ? (HttpStatusCode?) statusCode : null;
		}

		/// <summary>
		/// Gets the error code that corresponds to the specified HTTP status code.
		/// </summary>
		public static string TryGetErrorCode(HttpStatusCode statusCode)
		{
			switch ((int) statusCode)
			{
				case 403: return "NotAdmin";
				default: return null;
			}
		}

		static readonly IReadOnlyDictionary<string, int> s_errorToStatus = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
		{
			["NotAdmin"] = 403,
		};
	}
}
