// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;
using Facility.Core.Http;

namespace Facility.ExampleApi.Http
{
	/// <summary>
	/// Example service for widgets.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class HttpClientExampleApi : HttpClientService, IExampleApi
	{
		/// <summary>
		/// Creates the service.
		/// </summary>
		public HttpClientExampleApi(HttpClientServiceSettings settings = null)
			: base(settings, defaultBaseUri: new Uri("http://local.example.com/v1"))
		{
		}

		/// <summary>
		/// Gets widgets.
		/// </summary>
		public Task<ServiceResult<GetWidgetsResponseDto>> GetWidgetsAsync(GetWidgetsRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.GetWidgetsMapping, request, cancellationToken);
		}

		/// <summary>
		/// Creates a new widget.
		/// </summary>
		public Task<ServiceResult<CreateWidgetResponseDto>> CreateWidgetAsync(CreateWidgetRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.CreateWidgetMapping, request, cancellationToken);
		}

		/// <summary>
		/// Gets the specified widget.
		/// </summary>
		public Task<ServiceResult<GetWidgetResponseDto>> GetWidgetAsync(GetWidgetRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.GetWidgetMapping, request, cancellationToken);
		}

		/// <summary>
		/// Deletes the specified widget.
		/// </summary>
		public Task<ServiceResult<DeleteWidgetResponseDto>> DeleteWidgetAsync(DeleteWidgetRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.DeleteWidgetMapping, request, cancellationToken);
		}

		/// <summary>
		/// Edits widget.
		/// </summary>
		public Task<ServiceResult<EditWidgetResponseDto>> EditWidgetAsync(EditWidgetRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.EditWidgetMapping, request, cancellationToken);
		}

		/// <summary>
		/// Gets the specified widgets.
		/// </summary>
		public Task<ServiceResult<GetWidgetBatchResponseDto>> GetWidgetBatchAsync(GetWidgetBatchRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.GetWidgetBatchMapping, request, cancellationToken);
		}

		/// <summary>
		/// Gets the widget weight.
		/// </summary>
		[Obsolete]
		public Task<ServiceResult<GetWidgetWeightResponseDto>> GetWidgetWeightAsync(GetWidgetWeightRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.GetWidgetWeightMapping, request, cancellationToken);
		}

		/// <summary>
		/// Gets a widget preference.
		/// </summary>
		public Task<ServiceResult<GetPreferenceResponseDto>> GetPreferenceAsync(GetPreferenceRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.GetPreferenceMapping, request, cancellationToken);
		}

		/// <summary>
		/// Sets a widget preference.
		/// </summary>
		public Task<ServiceResult<SetPreferenceResponseDto>> SetPreferenceAsync(SetPreferenceRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.SetPreferenceMapping, request, cancellationToken);
		}

		/// <summary>
		/// Demonstrates the default HTTP behavior.
		/// </summary>
		public Task<ServiceResult<NotRestfulResponseDto>> NotRestfulAsync(NotRestfulRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.NotRestfulMapping, request, cancellationToken);
		}

		public Task<ServiceResult<KitchenResponseDto>> KitchenAsync(KitchenRequestDto request, CancellationToken cancellationToken)
		{
			return TrySendRequestAsync(ExampleApiHttpMapping.KitchenMapping, request, cancellationToken);
		}
	}
}
