// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using System.Net;

namespace Facility.ConformanceApi.Http
{
	/// <summary>
	/// Custom errors.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class HttpApiErrors
	{
		/// <summary>
		/// Gets the HTTP status code that corresponds to the specified error code.
		/// </summary>
		public static HttpStatusCode? TryGetHttpStatusCode(string errorCode) =>
			s_errorToStatus.TryGetValue(errorCode, out var statusCode) ? (HttpStatusCode?) statusCode : null;

		/// <summary>
		/// Gets the error code that corresponds to the specified HTTP status code.
		/// </summary>
		public static string TryGetErrorCode(HttpStatusCode statusCode)
		{
			switch ((int) statusCode)
			{
				case 403: return ApiErrors.NotAdmin;
				case 500: return ApiErrors.TooHappy;
				default: return null;
			}
		}

		private static readonly IReadOnlyDictionary<string, int> s_errorToStatus = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
		{
			[ApiErrors.NotAdmin] = 403,
			[ApiErrors.TooHappy] = 500,
		};
	}
}
