// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace EdgeCases
{
	/// <summary>
	/// Response for CustomHttp.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class CustomHttpResponseDto : ServiceDto<CustomHttpResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public CustomHttpResponseDto()
		{
		}

		[MessagePack.Key("value")]
		public string? Value { get; set; }

		[MessagePack.Key("extras")]
		public IReadOnlyDictionary<string, string>? Extras { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(CustomHttpResponseDto? other)
		{
			return other != null &&
				Value == other.Value &&
				ServiceDataUtility.AreEquivalentFieldValues(Extras, other.Extras);
		}
	}
}
