// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using ProtoBuf;

namespace EdgeCases
{
	/// <summary>
	/// A DTO.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	public sealed partial class DataDto : ServiceDto<DataDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public DataDto()
		{
		}

		[Newtonsoft.Json.JsonProperty("f")]
		[System.Text.Json.Serialization.JsonPropertyName("f")]
		[ProtoMember(1)]
		public string? Field { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(DataDto? other)
		{
			return other != null &&
				Field == other.Field;
		}
	}
}
