// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using Facility.Core;

namespace EdgeCases
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	internal static class EdgeCasesMethods
	{
		[Obsolete]
		public static readonly IServiceMethodInfo OldMethod =
			ServiceMethodInfo.Create<IEdgeCases, OldMethodRequestDto, OldMethodResponseDto>(
				"oldMethod", "EdgeCases", x => x.OldMethodAsync);
	}
}
