// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using Facility.Core;

namespace EdgeCases
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	internal static class EdgeCasesMethods
	{
		[Obsolete]
		public static readonly IServiceMethodInfo OldMethod =
			ServiceMethodInfo.Create<IEdgeCases, OldMethodRequestDto, OldMethodResponseDto>(
				"oldMethod", "EdgeCases", x => x.OldMethodAsync);

		public static readonly IServiceMethodInfo CustomHttp =
			ServiceMethodInfo.Create<IEdgeCases, CustomHttpRequestDto, CustomHttpResponseDto>(
				"customHttp", "EdgeCases", x => x.CustomHttpAsync);

		public static readonly IServiceMethodInfo SnakeMethod =
			ServiceMethodInfo.Create<IEdgeCases, SnakeMethodRequestDto, SnakeMethodResponseDto>(
				"snake_method", "EdgeCases", x => x.SnakeMethodAsync);

		public static readonly IServiceMethodInfo Misc =
			ServiceMethodInfo.Create<IEdgeCases, MiscRequestDto, MiscResponseDto>(
				"misc", "EdgeCases", x => x.MiscAsync);
	}
}
