// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System.Text.Json.Serialization;
using Facility.Core;

#pragma warning disable 612, 618 // member is obsolete
namespace EdgeCases
{
	[JsonSourceGenerationOptions(GenerationMode = JsonSourceGenerationMode.Metadata)]
	[JsonSerializable(typeof(ServiceErrorDto))]
	[JsonSerializable(typeof(ServiceObject))]
	[JsonSerializable(typeof(OldMethodRequestDto))]
	[JsonSerializable(typeof(OldMethodResponseDto))]
	[JsonSerializable(typeof(SnakeMethodRequestDto))]
	[JsonSerializable(typeof(SnakeMethodResponseDto))]
	[JsonSerializable(typeof(DataDto))]
	[JsonSerializable(typeof(OldEmptyDataDto))]
	[JsonSerializable(typeof(OldDataDto))]
	[JsonSerializable(typeof(SnakeDataDto))]
	internal sealed partial class EdgeCasesJsonSerializerContext : JsonSerializerContext
	{
	}
}
