// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;

namespace EdgeCases
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public partial interface IEdgeCases
	{
		/// <summary>
		/// An old method.
		/// </summary>
		[Obsolete]
		Task<ServiceResult<OldMethodResponseDto>> OldMethodAsync(OldMethodRequestDto request, CancellationToken cancellationToken);
	}
}
