// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using MessagePack;
using ProtoBuf;

#pragma warning disable 612, 618 // member is obsolete

namespace EdgeCases
{
	/// <summary>
	/// An old DTO.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class OldDataDto : ServiceDto<OldDataDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public OldDataDto()
		{
		}

		/// <summary>
		/// An old field.
		/// </summary>
		[Obsolete]
		[ProtoMember(1)]
		[Key(0)]
		public string? Old { get; set; }

		[Obsolete]
		[ProtoMember(2)]
		[Key(1)]
		public string? Older { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(OldDataDto? other)
		{
			return other != null &&
				Old == other.Old &&
				Older == other.Older;
		}
	}
}
