// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

#pragma warning disable 612, 618 // member is obsolete

namespace EdgeCases
{
	/// <summary>
	/// An old DTO.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class OldDataDto : ServiceDto<OldDataDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public OldDataDto()
		{
		}

		/// <summary>
		/// An old field.
		/// </summary>
		[Obsolete]
		[MessagePack.Key("old")]
		public string? Old { get; set; }

		[Obsolete]
		[MessagePack.Key("older")]
		public string? Older { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(OldDataDto? other)
		{
			return other != null &&
				Old == other.Old &&
				Older == other.Older;
		}
	}
}
