// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using Facility.Core;

namespace EdgeCases
{
	/// <summary>
	/// Some old errors.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class OldErrors
	{
		/// <summary>
		/// An old error.
		/// </summary>
		[Obsolete]
		public const string Old = "old";

		[Obsolete]
		public const string Older = "older";

		/// <summary>
		/// An old error.
		/// </summary>
		[Obsolete]
		public static ServiceErrorDto CreateOld(string message = null) => new ServiceErrorDto(Old, message ?? "An old error.");

		[Obsolete]
		public static ServiceErrorDto CreateOlder(string message = null) => new ServiceErrorDto(Older, message);
	}
}
