// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using ProtoBuf;

namespace EdgeCases
{
	/// <summary>
	/// An old DTO.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[Obsolete]
	[ProtoContract]
	public sealed partial class OldEmptyDataDto : ServiceDto<OldEmptyDataDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public OldEmptyDataDto()
		{
		}

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(OldEmptyDataDto? other)
		{
			return other != null;
		}
	}
}
