// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;

namespace EdgeCases
{
	/// <summary>
	/// Request for OldMethod.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class OldMethodRequestDto : ServiceDto<OldMethodRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public OldMethodRequestDto()
		{
		}

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(OldMethodRequestDto? other)
		{
			return other != null;
		}
	}
}
