// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EdgeCases
{
	/// <summary>
	/// Response for OldMethod.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class OldMethodResponseDto : ServiceDto<OldMethodResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public OldMethodResponseDto()
		{
		}

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(OldMethodResponseDto? other)
		{
			return other != null;
		}
	}
}
