// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace EdgeCases
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class SnakeDataDto : ServiceDto<SnakeDataDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public SnakeDataDto()
		{
		}

		[Newtonsoft.Json.JsonProperty("snake_field")]
		[System.Text.Json.Serialization.JsonPropertyName("snake_field")]
		[MessagePack.Key("snake_field")]
		public string? SnakeField { get; set; }

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(SnakeDataDto? other)
		{
			return other != null &&
				SnakeField == other.SnakeField;
		}
	}
}
