// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using MessagePack;
using ProtoBuf;

namespace Facility.Core
{
	/// <summary>
	/// An error.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class ServiceErrorDto : ServiceDto<ServiceErrorDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public ServiceErrorDto()
		{
		}

		/// <summary>
		/// The error code.
		/// </summary>
		[ProtoMember(1)]
		[Key(0)]
		public string? Code { get; set; }

		/// <summary>
		/// The error message.
		/// </summary>
		[ProtoMember(2)]
		[Key(1)]
		public string? Message { get; set; }

		/// <summary>
		/// Advanced error details.
		/// </summary>
		[Newtonsoft.Json.JsonProperty("details")]
		[System.Text.Json.Serialization.JsonPropertyName("details")]
		[ProtoMember(3)]
		[Key(2)]
		public ServiceObject? DetailsObject { get; set; }

		/// <summary>
		/// The inner error.
		/// </summary>
		[ProtoMember(4)]
		[Key(3)]
		public ServiceErrorDto? InnerError { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(ServiceErrorDto? other)
		{
			return other != null &&
				Code == other.Code &&
				Message == other.Message &&
				ServiceDataUtility.AreEquivalentObjects(DetailsObject, other.DetailsObject) &&
				ServiceDataUtility.AreEquivalentDtos(InnerError, other.InnerError);
		}
	}
}
