// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.Core
{
	/// <summary>
	/// An error.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class ServiceErrorDto : ServiceDto<ServiceErrorDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public ServiceErrorDto()
		{
		}

		/// <summary>
		/// The error code.
		/// </summary>
		public string Code { get; set; }

		/// <summary>
		/// The error message.
		/// </summary>
		public string Message { get; set; }

		/// <summary>
		/// Advanced error details.
		/// </summary>
		public JObject Details { get; set; }

		/// <summary>
		/// The inner error.
		/// </summary>
		public ServiceErrorDto InnerError { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(ServiceErrorDto other)
		{
			return other != null &&
				Code == other.Code &&
				Message == other.Message &&
				ServiceDataUtility.AreEquivalentObjects(Details, other.Details) &&
				ServiceDataUtility.AreEquivalentDtos(InnerError, other.InnerError);
		}
	}
}
