// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	public sealed partial class AnyDto : ServiceDto<AnyDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public AnyDto()
		{
		}

		[ProtoMember(1)]
		public string? String { get; set; }

		[ProtoMember(2)]
		public bool? Boolean { get; set; }

		[ProtoMember(3)]
		public double? Double { get; set; }

		[ProtoMember(4)]
		public int? Int32 { get; set; }

		[ProtoMember(5)]
		public long? Int64 { get; set; }

		[ProtoMember(6)]
		public decimal? Decimal { get; set; }

		[ProtoMember(7)]
		public byte[]? Bytes { get; set; }

		[ProtoMember(8)]
		public ServiceObject? Object { get; set; }

		[ProtoMember(9)]
		public ServiceErrorDto? Error { get; set; }

		[ProtoMember(10)]
		public AnyDto? Data { get; set; }

		[ProtoMember(11)]
		public Answer? Enum { get; set; }

		[ProtoMember(12)]
		public AnyArrayDto? Array { get; set; }

		[ProtoMember(13)]
		public AnyMapDto? Map { get; set; }

		[ProtoMember(14)]
		public AnyResultDto? Result { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(AnyDto? other)
		{
			return other != null &&
				String == other.String &&
				Boolean == other.Boolean &&
				Double == other.Double &&
				Int32 == other.Int32 &&
				Int64 == other.Int64 &&
				Decimal == other.Decimal &&
				ServiceDataUtility.AreEquivalentBytes(Bytes, other.Bytes) &&
				ServiceDataUtility.AreEquivalentObjects(Object, other.Object) &&
				ServiceDataUtility.AreEquivalentDtos(Error, other.Error) &&
				ServiceDataUtility.AreEquivalentDtos(Data, other.Data) &&
				Enum == other.Enum &&
				ServiceDataUtility.AreEquivalentDtos(Array, other.Array) &&
				ServiceDataUtility.AreEquivalentDtos(Map, other.Map) &&
				ServiceDataUtility.AreEquivalentDtos(Result, other.Result);
		}
	}
}
