// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using MessagePack;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class AnyMapDto : ServiceDto<AnyMapDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public AnyMapDto()
		{
		}

		[ProtoMember(1)]
		[Key(0)]
		public IReadOnlyDictionary<string, string>? String { get; set; }

		[ProtoMember(2)]
		[Key(1)]
		public IReadOnlyDictionary<string, bool>? Boolean { get; set; }

		[ProtoMember(3)]
		[Key(2)]
		public IReadOnlyDictionary<string, double>? Double { get; set; }

		[ProtoMember(4)]
		[Key(3)]
		public IReadOnlyDictionary<string, int>? Int32 { get; set; }

		[ProtoMember(5)]
		[Key(4)]
		public IReadOnlyDictionary<string, long>? Int64 { get; set; }

		[ProtoMember(6)]
		[Key(5)]
		public IReadOnlyDictionary<string, decimal>? Decimal { get; set; }

		[ProtoMember(7)]
		[Key(6)]
		public IReadOnlyDictionary<string, byte[]>? Bytes { get; set; }

		[ProtoMember(8)]
		[Key(7)]
		public IReadOnlyDictionary<string, ServiceObject>? Object { get; set; }

		[ProtoMember(9)]
		[Key(8)]
		public IReadOnlyDictionary<string, ServiceErrorDto>? Error { get; set; }

		[ProtoMember(10)]
		[Key(9)]
		public IReadOnlyDictionary<string, AnyDto>? Data { get; set; }

		[ProtoMember(11)]
		[Key(10)]
		public IReadOnlyDictionary<string, Answer>? Enum { get; set; }

		[ProtoMember(12)]
		[Key(11)]
		public IReadOnlyDictionary<string, IReadOnlyList<int>>? Array { get; set; }

		[ProtoMember(13)]
		[Key(12)]
		public IReadOnlyDictionary<string, IReadOnlyDictionary<string, int>>? Map { get; set; }

		[ProtoMember(14)]
		[Key(13)]
		public IReadOnlyDictionary<string, ServiceResult<int>>? Result { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(AnyMapDto? other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentFieldValues(String, other.String) &&
				ServiceDataUtility.AreEquivalentFieldValues(Boolean, other.Boolean) &&
				ServiceDataUtility.AreEquivalentFieldValues(Double, other.Double) &&
				ServiceDataUtility.AreEquivalentFieldValues(Int32, other.Int32) &&
				ServiceDataUtility.AreEquivalentFieldValues(Int64, other.Int64) &&
				ServiceDataUtility.AreEquivalentFieldValues(Decimal, other.Decimal) &&
				ServiceDataUtility.AreEquivalentFieldValues(Bytes, other.Bytes) &&
				ServiceDataUtility.AreEquivalentFieldValues(Object, other.Object) &&
				ServiceDataUtility.AreEquivalentFieldValues(Error, other.Error) &&
				ServiceDataUtility.AreEquivalentFieldValues(Data, other.Data) &&
				ServiceDataUtility.AreEquivalentFieldValues(Enum, other.Enum) &&
				ServiceDataUtility.AreEquivalentFieldValues(Array, other.Array) &&
				ServiceDataUtility.AreEquivalentFieldValues(Map, other.Map) &&
				ServiceDataUtility.AreEquivalentFieldValues(Result, other.Result);
		}
	}
}
