// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace Facility.ConformanceApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class AnyNullableDto : ServiceDto<AnyNullableDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public AnyNullableDto()
		{
		}

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<string?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("string")]
		public ServiceField<string?> String { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<bool?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("boolean")]
		public ServiceField<bool?> Boolean { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<double?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("double")]
		public ServiceField<double?> Double { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<int?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("int32")]
		public ServiceField<int?> Int32 { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<long?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("int64")]
		public ServiceField<long?> Int64 { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<decimal?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("decimal")]
		public ServiceField<decimal?> Decimal { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<byte[]?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("bytes")]
		public ServiceField<byte[]?> Bytes { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<ServiceObject?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("object")]
		public ServiceField<ServiceObject?> Object { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<ServiceErrorDto?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("error")]
		public ServiceField<ServiceErrorDto?> Error { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<AnyDto?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("data")]
		public ServiceField<AnyDto?> Data { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<Answer?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("enum")]
		public ServiceField<Answer?> Enum { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<IReadOnlyList<int>?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("array")]
		public ServiceField<IReadOnlyList<int>?> Array { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<IReadOnlyDictionary<string, int>?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("map")]
		public ServiceField<IReadOnlyDictionary<string, int>?> Map { get; set; }

		[Newtonsoft.Json.JsonProperty(DefaultValueHandling = Newtonsoft.Json.DefaultValueHandling.Ignore, NullValueHandling = Newtonsoft.Json.NullValueHandling.Include)]
		[ServiceFieldDefaultValueAttribute(typeof(ServiceField<ServiceResult<int>?>))]
		[System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
		[MessagePack.Key("result")]
		public ServiceField<ServiceResult<int>?> Result { get; set; }

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(AnyNullableDto? other)
		{
			return other != null &&
				String == other.String &&
				Boolean == other.Boolean &&
				Double == other.Double &&
				Int32 == other.Int32 &&
				Int64 == other.Int64 &&
				Decimal == other.Decimal &&
				Bytes == other.Bytes &&
				Object == other.Object &&
				Error == other.Error &&
				Data == other.Data &&
				Enum == other.Enum &&
				Array == other.Array &&
				Map == other.Map &&
				Result == other.Result;
		}
	}
}
