// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	public sealed partial class AnyResultDto : ServiceDto<AnyResultDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public AnyResultDto()
		{
		}

		[ProtoMember(1)]
		public ServiceResult<string>? String { get; set; }

		[ProtoMember(2)]
		public ServiceResult<bool>? Boolean { get; set; }

		[ProtoMember(3)]
		public ServiceResult<double>? Double { get; set; }

		[ProtoMember(4)]
		public ServiceResult<int>? Int32 { get; set; }

		[ProtoMember(5)]
		public ServiceResult<long>? Int64 { get; set; }

		[ProtoMember(6)]
		public ServiceResult<decimal>? Decimal { get; set; }

		[ProtoMember(7)]
		public ServiceResult<byte[]>? Bytes { get; set; }

		[ProtoMember(8)]
		public ServiceResult<ServiceObject>? Object { get; set; }

		[ProtoMember(9)]
		public ServiceResult<ServiceErrorDto>? Error { get; set; }

		[ProtoMember(10)]
		public ServiceResult<AnyDto>? Data { get; set; }

		[ProtoMember(11)]
		public ServiceResult<Answer>? Enum { get; set; }

		[ProtoMember(12)]
		public ServiceResult<IReadOnlyList<int>>? Array { get; set; }

		[ProtoMember(13)]
		public ServiceResult<IReadOnlyDictionary<string, int>>? Map { get; set; }

		[ProtoMember(14)]
		public ServiceResult<ServiceResult<int>>? Result { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(AnyResultDto? other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentResults(String, other.String) &&
				ServiceDataUtility.AreEquivalentResults(Boolean, other.Boolean) &&
				ServiceDataUtility.AreEquivalentResults(Double, other.Double) &&
				ServiceDataUtility.AreEquivalentResults(Int32, other.Int32) &&
				ServiceDataUtility.AreEquivalentResults(Int64, other.Int64) &&
				ServiceDataUtility.AreEquivalentResults(Decimal, other.Decimal) &&
				ServiceDataUtility.AreEquivalentResults(Bytes, other.Bytes) &&
				ServiceDataUtility.AreEquivalentResults(Object, other.Object) &&
				ServiceDataUtility.AreEquivalentResults(Error, other.Error) &&
				ServiceDataUtility.AreEquivalentResults(Data, other.Data) &&
				ServiceDataUtility.AreEquivalentResults(Enum, other.Enum) &&
				ServiceDataUtility.AreEquivalentResults(Array, other.Array) &&
				ServiceDataUtility.AreEquivalentResults(Map, other.Map) &&
				ServiceDataUtility.AreEquivalentResults(Result, other.Result);
		}
	}
}
