// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using MessagePack;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class AnyResultDto : ServiceDto<AnyResultDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public AnyResultDto()
		{
		}

		[ProtoMember(1)]
		[Key(0)]
		public ServiceResult<string>? String { get; set; }

		[ProtoMember(2)]
		[Key(1)]
		public ServiceResult<bool>? Boolean { get; set; }

		[ProtoMember(3)]
		[Key(2)]
		public ServiceResult<double>? Double { get; set; }

		[ProtoMember(4)]
		[Key(3)]
		public ServiceResult<int>? Int32 { get; set; }

		[ProtoMember(5)]
		[Key(4)]
		public ServiceResult<long>? Int64 { get; set; }

		[ProtoMember(6)]
		[Key(5)]
		public ServiceResult<decimal>? Decimal { get; set; }

		[ProtoMember(7)]
		[Key(6)]
		public ServiceResult<byte[]>? Bytes { get; set; }

		[ProtoMember(8)]
		[Key(7)]
		public ServiceResult<ServiceObject>? Object { get; set; }

		[ProtoMember(9)]
		[Key(8)]
		public ServiceResult<ServiceErrorDto>? Error { get; set; }

		[ProtoMember(10)]
		[Key(9)]
		public ServiceResult<AnyDto>? Data { get; set; }

		[ProtoMember(11)]
		[Key(10)]
		public ServiceResult<Answer>? Enum { get; set; }

		[ProtoMember(12)]
		[Key(11)]
		public ServiceResult<IReadOnlyList<int>>? Array { get; set; }

		[ProtoMember(13)]
		[Key(12)]
		public ServiceResult<IReadOnlyDictionary<string, int>>? Map { get; set; }

		[ProtoMember(14)]
		[Key(13)]
		public ServiceResult<ServiceResult<int>>? Result { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(AnyResultDto? other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentResults(String, other.String) &&
				ServiceDataUtility.AreEquivalentResults(Boolean, other.Boolean) &&
				ServiceDataUtility.AreEquivalentResults(Double, other.Double) &&
				ServiceDataUtility.AreEquivalentResults(Int32, other.Int32) &&
				ServiceDataUtility.AreEquivalentResults(Int64, other.Int64) &&
				ServiceDataUtility.AreEquivalentResults(Decimal, other.Decimal) &&
				ServiceDataUtility.AreEquivalentResults(Bytes, other.Bytes) &&
				ServiceDataUtility.AreEquivalentResults(Object, other.Object) &&
				ServiceDataUtility.AreEquivalentResults(Error, other.Error) &&
				ServiceDataUtility.AreEquivalentResults(Data, other.Data) &&
				ServiceDataUtility.AreEquivalentResults(Enum, other.Enum) &&
				ServiceDataUtility.AreEquivalentResults(Array, other.Array) &&
				ServiceDataUtility.AreEquivalentResults(Map, other.Map) &&
				ServiceDataUtility.AreEquivalentResults(Result, other.Result);
		}

		static AnyResultDto()
		{
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<string>>(false).SetSurrogate(typeof(ServiceResultSurrogate<string>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<bool>>(false).SetSurrogate(typeof(ServiceResultSurrogate<bool>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<double>>(false).SetSurrogate(typeof(ServiceResultSurrogate<double>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<int>>(false).SetSurrogate(typeof(ServiceResultSurrogate<int>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<long>>(false).SetSurrogate(typeof(ServiceResultSurrogate<long>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<decimal>>(false).SetSurrogate(typeof(ServiceResultSurrogate<decimal>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<byte[]>>(false).SetSurrogate(typeof(ServiceResultSurrogate<byte[]>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<ServiceObject>>(false).SetSurrogate(typeof(ServiceResultSurrogate<ServiceObject>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<ServiceErrorDto>>(false).SetSurrogate(typeof(ServiceResultSurrogate<ServiceErrorDto>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<AnyDto>>(false).SetSurrogate(typeof(ServiceResultSurrogate<AnyDto>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<Answer>>(false).SetSurrogate(typeof(ServiceResultSurrogate<Answer>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<IReadOnlyList<int>>>(false).SetSurrogate(typeof(ServiceResultSurrogate<IReadOnlyList<int>>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<IReadOnlyDictionary<string, int>>>(false).SetSurrogate(typeof(ServiceResultSurrogate<IReadOnlyDictionary<string, int>>));
			ProtoBuf.Meta.RuntimeTypeModel.Default.Add<ServiceResult<ServiceResult<int>>>(false).SetSurrogate(typeof(ServiceResultSurrogate<ServiceResult<int>>));
		}
	}
}
