// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using Facility.Core;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Custom errors.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class ApiErrors
	{
		/// <summary>
		/// The user is not an administrator.
		/// </summary>
		public const string NotAdmin = "NotAdmin";

		/// <summary>
		/// I'm "too" 😄!
		/// </summary>
		public const string TooHappy = "TooHappy";

		/// <summary>
		/// The user is not an administrator.
		/// </summary>
		public static ServiceErrorDto CreateNotAdmin(string message = null) => new ServiceErrorDto(NotAdmin, message ?? "The user is not an administrator.");

		/// <summary>
		/// I'm "too" 😄!
		/// </summary>
		public static ServiceErrorDto CreateTooHappy(string message = null) => new ServiceErrorDto(TooHappy, message ?? "I'm \"too\" 😄!");
	}
}
