// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
#if NET8_0_OR_GREATER
using Facility.Core;

#pragma warning disable 612, 618 // member is obsolete
namespace Facility.ConformanceApi
{
	/// <summary>
	/// The JSON service serializer.
	/// </summary>
	public sealed class ConformanceApiJsonServiceSerializer : SystemTextJsonContextServiceSerializer
	{
		/// <summary>
		/// The instance of the JSON service serializer.
		/// </summary>
		public static readonly ConformanceApiJsonServiceSerializer Instance = new ConformanceApiJsonServiceSerializer();

		private ConformanceApiJsonServiceSerializer()
			: base(new ConformanceApiJsonSerializerContext(SystemTextJsonServiceSerializer.CreateJsonSerializerOptions()))
		{
		}
	}
}
#endif
