// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using MessagePack;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for DeleteWidget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class DeleteWidgetResponseDto : ServiceDto<DeleteWidgetResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public DeleteWidgetResponseDto()
		{
		}

		/// <summary>
		/// The widget was not found.
		/// </summary>
		[ProtoMember(1)]
		[Key(0)]
		public bool? NotFound { get; set; }

		/// <summary>
		/// The widget no longer has the specified ETag.
		/// </summary>
		[ProtoMember(2)]
		[Key(1)]
		public bool? Conflict { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(DeleteWidgetResponseDto? other)
		{
			return other != null &&
				NotFound == other.NotFound &&
				Conflict == other.Conflict;
		}
	}
}
