// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Request for Fibonacci.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class FibonacciRequestDto : ServiceDto<FibonacciRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public FibonacciRequestDto()
		{
		}

		[MessagePack.Key("count")]
		public int? Count { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(FibonacciRequestDto? other)
		{
			return other != null &&
				Count == other.Count;
		}

		/// <summary>
		/// Validates the DTO.
		/// </summary>
		public override bool Validate(out string? errorMessage)
		{
			errorMessage = GetValidationErrorMessage();
			return errorMessage == null;
		}

		private string? GetValidationErrorMessage()
		{
			if (Count == null)
				return ServiceDataUtility.GetRequiredFieldErrorMessage("count");

			return null;
		}
	}
}
