// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using MessagePack;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for GetApiInfo.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class GetApiInfoResponseDto : ServiceDto<GetApiInfoResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetApiInfoResponseDto()
		{
		}

		/// <summary>
		/// The name of the service.
		/// </summary>
		[ProtoMember(1)]
		[Key(0)]
		public string? Service { get; set; }

		/// <summary>
		/// The version of the service.
		/// </summary>
		[ProtoMember(2)]
		[Key(1)]
		public string? Version { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetApiInfoResponseDto? other)
		{
			return other != null &&
				Service == other.Service &&
				Version == other.Version;
		}
	}
}
