// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Request for GetExternalWidgets.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class GetExternalWidgetsRequestDto : ServiceDto<GetExternalWidgetsRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetExternalWidgetsRequestDto()
		{
		}

		/// <summary>
		/// The query.
		/// </summary>
		[MessagePack.Key("query")]
		public string? Query { get; set; }

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetExternalWidgetsRequestDto? other)
		{
			return other != null &&
				Query == other.Query;
		}
	}
}
