// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for GetExternalWidgets.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class GetExternalWidgetsResponseDto : ServiceDto<GetExternalWidgetsResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetExternalWidgetsResponseDto()
		{
		}

		/// <summary>
		/// The external widgets.
		/// </summary>
		[MessagePack.Key("externalWidgets")]
		public IReadOnlyList<Facility.ConformanceApi.External.TestExternalDto>? ExternalWidgets { get; set; }

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetExternalWidgetsResponseDto? other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentFieldValues(ExternalWidgets, other.ExternalWidgets);
		}
	}
}
