// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for MirrorText.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	public sealed partial class MirrorTextResponseDto : ServiceDto<MirrorTextResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public MirrorTextResponseDto()
		{
		}

		[ProtoMember(1)]
		public string? Content { get; set; }

		[ProtoMember(2)]
		public string? Type { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(MirrorTextResponseDto? other)
		{
			return other != null &&
				Content == other.Content &&
				Type == other.Type;
		}
	}
}
