// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using MessagePack;
using ProtoBuf;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for MirrorBytes.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[ProtoContract]
	[MessagePackObject]
	public sealed partial class MirrorBytesResponseDto : ServiceDto<MirrorBytesResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public MirrorBytesResponseDto()
		{
		}

		[ProtoMember(1)]
		[Key(0)]
		public byte[]? Content { get; set; }

		[ProtoMember(2)]
		[Key(1)]
		public string? Type { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(MirrorBytesResponseDto? other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentBytes(Content, other.Content) &&
				Type == other.Type;
		}
	}
}
