// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for Mixed.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class MixedResponseDto : ServiceDto<MixedResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public MixedResponseDto()
		{
		}

		public string Header { get; set; }

		public string Normal { get; set; }

		public JObject Body { get; set; }

		public bool? Empty { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(MixedResponseDto other)
		{
			return other != null &&
				Header == other.Header &&
				Normal == other.Normal &&
				ServiceDataUtility.AreEquivalentObjects(Body, other.Body) &&
				Empty == other.Empty;
		}
	}
}
