// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Response for Mixed.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class MixedResponseDto : ServiceDto<MixedResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public MixedResponseDto()
		{
		}

		[MessagePack.Key("header")]
		public string? Header { get; set; }

		[MessagePack.Key("normal")]
		public string? Normal { get; set; }

		[MessagePack.Key("body")]
		public ServiceObject? Body { get; set; }

		[MessagePack.Key("empty")]
		public bool? Empty { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(MixedResponseDto? other)
		{
			return other != null &&
				Header == other.Header &&
				Normal == other.Normal &&
				ServiceDataUtility.AreEquivalentObjects(Body, other.Body) &&
				Empty == other.Empty;
		}
	}
}
