// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Request for Required.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class RequiredRequestDto : ServiceDto<RequiredRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public RequiredRequestDto()
		{
		}

		public string? Query { get; set; }

		public string? Normal { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(RequiredRequestDto? other)
		{
			return other != null &&
				Query == other.Query &&
				Normal == other.Normal;
		}

		/// <summary>
		/// Validates the DTO.
		/// </summary>
		public override bool Validate(out string? errorMessage)
		{
			errorMessage = GetValidationErrorMessage();
			return errorMessage == null;
		}

		private string? GetValidationErrorMessage()
		{
			if (Query == null)
				return ServiceDataUtility.GetRequiredFieldErrorMessage("query");
			if (Normal == null)
				return ServiceDataUtility.GetRequiredFieldErrorMessage("normal");

			return null;
		}
	}
}
