// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// Request for Required.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class RequiredRequestDto : ServiceDto<RequiredRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public RequiredRequestDto()
		{
		}

		[MessagePack.Key("query")]
		public string? Query { get; set; }

		[MessagePack.Key("normal")]
		public string? Normal { get; set; }

		[MessagePack.Key("widget")]
		public WidgetDto? Widget { get; set; }

		[MessagePack.Key("widgets")]
		public IReadOnlyList<WidgetDto>? Widgets { get; set; }

		[MessagePack.Key("widgetMatrix")]
		public IReadOnlyList<IReadOnlyList<WidgetDto>>? WidgetMatrix { get; set; }

		[MessagePack.Key("widgetResult")]
		public ServiceResult<WidgetDto>? WidgetResult { get; set; }

		[MessagePack.Key("widgetResults")]
		public IReadOnlyList<ServiceResult<WidgetDto>>? WidgetResults { get; set; }

		[MessagePack.Key("widgetMap")]
		public IReadOnlyDictionary<string, WidgetDto>? WidgetMap { get; set; }

		[MessagePack.Key("hasWidget")]
		public HasWidgetDto? HasWidget { get; set; }

		[MessagePack.Key("point")]
		public IReadOnlyList<double>? Point { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(RequiredRequestDto? other)
		{
			return other != null &&
				Query == other.Query &&
				Normal == other.Normal &&
				ServiceDataUtility.AreEquivalentDtos(Widget, other.Widget) &&
				ServiceDataUtility.AreEquivalentFieldValues(Widgets, other.Widgets) &&
				ServiceDataUtility.AreEquivalentFieldValues(WidgetMatrix, other.WidgetMatrix) &&
				ServiceDataUtility.AreEquivalentResults(WidgetResult, other.WidgetResult) &&
				ServiceDataUtility.AreEquivalentFieldValues(WidgetResults, other.WidgetResults) &&
				ServiceDataUtility.AreEquivalentFieldValues(WidgetMap, other.WidgetMap) &&
				ServiceDataUtility.AreEquivalentDtos(HasWidget, other.HasWidget) &&
				ServiceDataUtility.AreEquivalentFieldValues(Point, other.Point);
		}

		/// <summary>
		/// Validates the DTO.
		/// </summary>
		public override bool Validate(out string? errorMessage)
		{
			errorMessage = GetValidationErrorMessage();
			return errorMessage == null;
		}

		private string? GetValidationErrorMessage()
		{
			if (Query == null)
				return ServiceDataUtility.GetRequiredFieldErrorMessage("query");
			if (Normal == null)
				return ServiceDataUtility.GetRequiredFieldErrorMessage("normal");

			if (Point != null && Point.Count < 2)
				return ServiceDataUtility.GetInvalidFieldErrorMessage("point", "Count must be at least 2.");
			if (Point != null && Point.Count > 2)
				return ServiceDataUtility.GetInvalidFieldErrorMessage("point", "Count must be at most 2.");

			string? errorMessage;
			if (!ServiceDataUtility.ValidateFieldValue(Widget, "widget", out errorMessage))
				return errorMessage!;
			if (!ServiceDataUtility.ValidateFieldValue(Widgets, "widgets", out errorMessage))
				return errorMessage!;
			if (!ServiceDataUtility.ValidateFieldValue(WidgetMatrix, "widgetMatrix", out errorMessage))
				return errorMessage!;
			if (!ServiceDataUtility.ValidateFieldValue(WidgetResult, "widgetResult", out errorMessage))
				return errorMessage!;
			if (!ServiceDataUtility.ValidateFieldValue(WidgetResults, "widgetResults", out errorMessage))
				return errorMessage!;
			if (!ServiceDataUtility.ValidateFieldValue(WidgetMap, "widgetMap", out errorMessage))
				return errorMessage!;
			if (!ServiceDataUtility.ValidateFieldValue(HasWidget, "hasWidget", out errorMessage))
				return errorMessage!;

			return null;
		}
	}
}
