// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using Facility.Core;

namespace Facility.ConformanceApi
{
	/// <summary>
	/// A widget.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class WidgetDto : ServiceDto<WidgetDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public WidgetDto()
		{
		}

		/// <summary>
		/// A unique identifier for the widget.
		/// </summary>
		public int? Id { get; set; }

		/// <summary>
		/// The name of the widget.
		/// </summary>
		public string? Name { get; set; }

		private static readonly Regex s_validNameRegex = new Regex("^[_a-zA-Z0-9]+$", RegexOptions.CultureInvariant);

		/// <summary>
		/// Returns the DTO as JSON.
		/// </summary>
		public override string ToString() => SystemTextJsonServiceSerializer.Instance.ToJson(this);

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(WidgetDto? other)
		{
			return other != null &&
				Id == other.Id &&
				Name == other.Name;
		}

		/// <summary>
		/// Validates the DTO.
		/// </summary>
		public override bool Validate(out string? errorMessage)
		{
			errorMessage = GetValidationErrorMessage();
			return errorMessage == null;
		}

		private string? GetValidationErrorMessage()
		{
			if (Name == null)
				return ServiceDataUtility.GetRequiredFieldErrorMessage("name");

			if (Id != null && Id < 0)
				return ServiceDataUtility.GetInvalidFieldErrorMessage("id", "Must be at least 0.");
			if (Name != null && Name.Length < 1)
				return ServiceDataUtility.GetInvalidFieldErrorMessage("name", "Length must be at least 1.");
			if (Name != null && Name.Length > 10)
				return ServiceDataUtility.GetInvalidFieldErrorMessage("name", "Length must be at most 10.");
			if (Name != null && !s_validNameRegex.IsMatch(Name))
				return ServiceDataUtility.GetInvalidFieldErrorMessage("name", $"Must match regular expression: {s_validNameRegex}");

			return null;
		}
	}
}
