// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using Facility.Core;
using Facility.Core.MessagePack;

namespace EdgeCases.ExternTypes
{
	/// <summary>
	/// A DTO used by the EdgeCases FSD as an external data type.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	[MessagePack.MessagePackObject]
	public sealed partial class ExternalDataDto : ServiceDto<ExternalDataDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public ExternalDataDto()
		{
		}

		[MessagePack.Key("name")]
		public string? Name { get; set; }

		/// <summary>
		/// The JSON serializer.
		/// </summary>
		protected override JsonServiceSerializer JsonSerializer => SystemTextJsonServiceSerializer.Instance;

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(ExternalDataDto? other)
		{
			return other != null &&
				Name == other.Name;
		}
	}
}
