// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Request for GetInfo.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetInfoRequestDto : ServiceDto<GetInfoRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetInfoRequestDto()
		{
		}

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetInfoRequestDto other)
		{
			return other != null;
		}
	}
}
