// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Response for GetInfo.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetInfoResponseDto : ServiceDto<GetInfoResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetInfoResponseDto()
		{
		}

		/// <summary>
		/// The name of the service.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetInfoResponseDto other)
		{
			return other != null &&
				Name == other.Name;
		}
	}
}
