// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Request for GetPreference.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class GetPreferenceRequestDto : ServiceDto<GetPreferenceRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public GetPreferenceRequestDto()
		{
		}

		/// <summary>
		/// The preference key.
		/// </summary>
		public string Key { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(GetPreferenceRequestDto other)
		{
			return other != null &&
				Key == other.Key;
		}
	}
}
