// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Response for Kitchen.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class KitchenResponseDto : ServiceDto<KitchenResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public KitchenResponseDto()
		{
		}

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(KitchenResponseDto other)
		{
			return other != null;
		}
	}
}
