// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Request for Kitchen.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class KitchenRequestDto : ServiceDto<KitchenRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public KitchenRequestDto()
		{
		}

		public KitchenSinkDto Sink { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(KitchenRequestDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentDtos(Sink, other.Sink);
		}
	}
}
