// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Facility.ExampleApi
{
	/// <summary>
	/// Request for Transform.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class TransformRequestDto : ServiceDto<TransformRequestDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public TransformRequestDto()
		{
		}

		public JObject Before { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(TransformRequestDto other)
		{
			return other != null &&
				ServiceDataUtility.AreEquivalentObjects(Before, other.Before);
		}
	}
}
