// DO NOT EDIT: generated by fsdgencsharp
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Net.Http;
using Facility.Core;
using Facility.Core.Http;
using Newtonsoft.Json.Linq;

#pragma warning disable 612, 618 // member is obsolete

namespace EdgeCases.Http
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class EdgeCasesHttpMapping
	{
		/// <summary>
		/// An old method.
		/// </summary>
		[Obsolete]
		public static readonly HttpMethodMapping<OldMethodRequestDto, OldMethodResponseDto> OldMethodMapping =
			new HttpMethodMapping<OldMethodRequestDto, OldMethodResponseDto>.Builder
			{
				HttpMethod = HttpMethod.Post,
				Path = "/oldMethod",
				ResponseMappings =
				{
					new HttpResponseMapping<OldMethodResponseDto>.Builder
					{
						StatusCode = (HttpStatusCode) 200,
					}.Build(),
				},
			}.Build();
	}
}
