// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Net;

#pragma warning disable 612, 618 // member is obsolete

namespace EdgeCases.Http
{
	/// <summary>
	/// Some old errors.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class HttpOldErrors
	{
		/// <summary>
		/// Gets the HTTP status code that corresponds to the specified error code.
		/// </summary>
		public static HttpStatusCode? TryGetHttpStatusCode(string? errorCode) =>
			s_errorToStatus.TryGetValue(errorCode ?? "", out var statusCode) ? (HttpStatusCode?) statusCode : null;

		/// <summary>
		/// Gets the error code that corresponds to the specified HTTP status code.
		/// </summary>
		public static string? TryGetErrorCode(HttpStatusCode statusCode)
		{
			switch ((int) statusCode)
			{
			case 500:
				return OldErrors.Old;
			default:
				return null;
			}
		}

		private static readonly IReadOnlyDictionary<string, int> s_errorToStatus = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase)
		{
			{ OldErrors.Old, 500 },
			{ OldErrors.Older, 500 },
		};
	}
}
