// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
#nullable enable
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;
using Facility.Core.Http;

namespace EdgeCases.Http
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class HttpClientEdgeCases : HttpClientService, IEdgeCases
	{
		/// <summary>
		/// Creates the service.
		/// </summary>
		public HttpClientEdgeCases(HttpClientServiceSettings? settings = null)
			: base(settings, s_defaults)
		{
		}

		/// <summary>
		/// An old method.
		/// </summary>
		[Obsolete]
		public Task<ServiceResult<OldMethodResponseDto>> OldMethodAsync(OldMethodRequestDto request, CancellationToken cancellationToken = default) =>
			TrySendRequestAsync(EdgeCasesHttpMapping.OldMethodMapping, request, cancellationToken);

		private static readonly HttpClientServiceDefaults s_defaults = new HttpClientServiceDefaults
		{
			JsonSerializer = SystemTextJsonServiceSerializer.Instance,
		};
	}
}
